### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by Renari**

### CODE REVIEW

**Comment by xywang68** [comment]
Hi, Renari, the two scripts already has node as their default shell via
```
#!/usr/bin/env node
```
therefore they can be executed directly, and default shell is not needed.

**Comment by Renari** [comment]
Unfortunately, this does not work on windows and you will get an error that `bin` is an unrecognized program.

**Comment by xywang68** [comment]
I see. I have update package.json just today. Please re-pull and submit a new PR.
Also, appreciate it you can add simple test scripts using my examples.

**Comment by Renari** [comment]
Still working on this, I will let you know when finished.

**Review by xywang68 — APPROVED** [review]

**Comment by xywang68** [comment]
do you still need to node prefix for the npm run download command? Please add if it is necessary for windows.
I develop this mainly for Linux, but I would like to see it also work for Windows. Your efforts are greatly appreciated.

**Comment by Renari** [comment]
Yes it is still needed for the download command. I think electron can be used to make the tests work on both platforms but I'll need to find more time to work on that.

**Pull request merged**
